CREATE TABLE `CENA` (
  `ID` BIGINT AUTO_INCREMENT,
  `PRODUKT` VARCHAR(1024) NOT NULL,
  `CENA` FLOAT NOT NULL,
  `KRAJ` VARCHAR(3) NOT NULL,
  `UZYTKOWNIK_ID` BIGINT NOT NULL,
  `DODANO` DATETIME,
  CONSTRAINT `PK_Cena` PRIMARY KEY (`ID`)
);

CREATE TRIGGER `CENA_DODANO_DEFAULT` BEFORE INSERT ON `CENA`
  FOR EACH ROW SET NEW.`DODANO` = CURRENT_TIMESTAMP;

-- DROP TRIGGER `CENA_DODANO_DEFAULT`;

-- DROP TABLE `CENA`;